# ターミナルカラーの設定
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# デフォルトのPrefixキーを削除
unbind C-b

# Prefixキーの設定
set-option -g prefix C-o

# tmux.conf 
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# viモードを使用する
set-window-option -g mode-keys vi

# ウィンドウとペインの番号を 1 から開始
set -g base-index 1
setw -g pane-base-index 1

# ウィンドウを閉じた時に番号を詰める
set-option -g renumber-windows on

# [prefix] + [-] でペインを横に分割する
bind - split-window -v

# [prefix] + [|] でペインを縦に分割する
bind | split-window -h

# ペインの切り替え
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# ペインサイズ変更
bind -r C-h resize-pane -L 5 # 左方向にリサイズ
bind -r C-l resize-pane -R 5 # 右方向にリサイズ
bind -r C-j resize-pane -D 5 # 下方向にリサイズ
bind -r C-k resize-pane -U 5 # 上方向にリサイズ

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel
set -s copy-command 'pbcopy'

# status-right のフォーマットを指定する。
set-option -g status-right " %Y/%m/%d %a %H:%M #[default]"

# 履歴上限
set-option -g history-limit 65535

# ペイン番号表示時間を長くする
set -g display-panes-time 10000

# ステータスバー配置
set -g status-position bottom # 上に配置

# キー入力のブロードキャスト
bind a setw synchronize-panes \; display "synchronize-panes #{?pane_synchronized,on,off}"

# Ctrl + l でバッファ削除
bind -n C-l send-keys C-l \; send-keys -R \; clear-history

# Metaキー遅延させない
set -sg escape-time 0

#### COLOUR

# default statusbar colors
set-option -g status-style bg=colour235,fg=colour136,default

# default window title colors
set-window-option -g window-status-style fg=colour244,bg=colour234,dim

# active window title colors
set-window-option -g window-status-current-style fg=colour166,bg=default,bright

# pane border
set-option -g pane-border-style fg=colour235 #base02
set-option -g pane-active-border-style fg=colour136,bg=colour235

# message text
set-option -g message-style bg=colour235,fg=colour166

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green

# Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'

# ログ収集プラグイン
set -g @plugin 'tmux-plugins/tmux-logging'

run-shell '~/.tmux/plugins/tpm/tpm'

source "/opt/homebrew/lib/python3.11/site-packages/powerline/bindings/tmux/powerline.conf"
run-shell "powerline-daemon -q"

source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf
